/**
 * resca
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Friend from './Friend';





/**
* The Content model module.
* @module model/Content
* @version 1.0.0
*/
export default class Content {
    /**
    * Constructs a new <code>Content</code>.
    * @alias module:model/Content
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Content</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Content} obj Optional instance to populate.
    * @return {module:model/Content} The populated <code>Content</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Content();

            
            
            

            if (data.hasOwnProperty('friends')) {
                obj['friends'] = ApiClient.convertToType(data['friends'], [Friend]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Friend>} friends
    */
    friends = undefined;








}


