/**
 * resca
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Friend model module.
* @module model/Friend
* @version 1.0.0
*/
export default class Friend {
    /**
    * Constructs a new <code>Friend</code>.
    * @alias module:model/Friend
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Friend</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Friend} obj Optional instance to populate.
    * @return {module:model/Friend} The populated <code>Friend</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Friend();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} gender
    */
    gender = undefined;
    /**
    * @member {String} status
    */
    status = undefined;
    /**
    * @member {String} avatar
    */
    avatar = undefined;








}


