/* eslint-disable */
/**
 * resca
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The LoginResult model module.
* @module model/LoginResult
* @version 1.0.0
*/
export default class LoginResult {
    /**
    * Constructs a new <code>LoginResult</code>.
    * @alias module:model/LoginResult
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>LoginResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LoginResult} obj Optional instance to populate.
    * @return {module:model/LoginResult} The populated <code>LoginResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginResult();

            
            
            

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} token
    */
    token = undefined;








}


