/**
 * resca
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PingPong model module.
* @module model/PingPong
* @version 1.0.0
*/
export default class PingPong {
    /**
    * Constructs a new <code>PingPong</code>.
    * @alias module:model/PingPong
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PingPong</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PingPong} obj Optional instance to populate.
    * @return {module:model/PingPong} The populated <code>PingPong</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PingPong();

            
            
            

            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} result
    */
    result = undefined;








}


