/**
 * resca
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PingPong from '../model/PingPong';

/**
* PingPong service.
* @module api/PingPongApi
* @version 1.0.0
*/
export default class PingPongApi {

    /**
    * Constructs a new PingPongApi. 
    * @alias module:api/PingPongApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * ping api server
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PingPong} and HTTP response
     */
    pingPongWithHttpInfo() {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PingPong;

      return this.apiClient.callApi(
        '/ping', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * ping api server
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PingPong}
     */
    pingPong() {
      return this.pingPongWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
