export default {
	NETWORK_SPEED_TEST_START: 'NETWORK_SPEED_TEST_START',
	NETWORK_SPEED_TEST_CLEAR: 'NETWORK_SPEED_TEST_CLEAR',
	NETWORK_SPEED_TEST_REQUEST: 'NETWORK_SPEED_TEST_REQUEST',
	NETWORK_SPEED_TEST_SUCCESS: 'NETWORK_SPEED_TEST_SUCCESS',
	NETWORK_SPEED_TEST_FAILURE: 'NETWORK_SPEED_TEST_FAILURE',
	NETWORK_SPEED_TEST_CANCEL_REQUEST: 'NETWORK_SPEED_TEST_CANCEL_REQUEST'
};
