swagger: '2.0'
info:
  title: resca
  version: 1.0.0
host: 127.0.0.1:7443
schemes:
  - http
basePath: /api/v0
produces:
  - application/json
security:
  - basic: []
  - oauth: []
securityDefinitions:
  basic:
    type: basic
    flow: password
  oauth:
    type: oauth2
    flow: password
paths:
  /ping:
    get:
      summary: ping api server
      operationId: pingPong
      tags:
        - pingPong
      responses:
        200:
          description: returns pong
          schema:
              $ref: '#/definitions/PingPong'
  /login:
    get:
      summary: login server
      operationId: login
      tags:
        - login
      responses:
        200:
          description: returns token
          schema:
              $ref: '#/definitions/LoginResult'
definitions:
  PingPong:
    type: object
    properties:
      result:
        type: string
  LoginResult:
    type: object
    properties:
      token:
        type: string

